name: nf5503_flutter
description: M5Stack NF5503 Android barcode scanner and thermal/label printer Flutter plugin.
version: 0.0.1
topics:
  - android
  - barcode
  - printer
  - thermal-printer
  - m5stack
platforms:
  android:

environment:
  sdk: ^3.12.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.m5stack.nf5503_flutter
        pluginClass: Nf5503FlutterPlugin
